<a href="https://colab.research.google.com/github/Ibrah-N/Deep-Learning-Projects-Computer-Vision/blob/main/pytorch_01_tensors_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensors Initialization

In [1]:
import torch

In [2]:
# empty tensor


t_1 = torch.empty(size=(3, 3))
t_1

tensor([[2.1715e-18, 2.6824e+23, 5.4658e+22],
        [8.3187e+20, 4.1951e-08, 2.0449e+23],
        [1.0074e-11, 1.3284e-08, 3.4016e+21]])

In [4]:
# check tensor type

print(type(t_1))
print(t_1.dtype)

<class 'torch.Tensor'>
torch.float32


In [6]:
# zero tensor

t_2 = torch.zeros(size=(3, 3))
t_2

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [12]:
# rand tensor

t_3 = torch.rand(3, 3)
t_4 = torch.randn(4, 4)
t_5 = torch.randint(size=(2, 2), low=0, high=5)

print(t_3)
print(t_4)
print(t_5)

tensor([[0.7677, 0.4840, 0.7028],
        [0.4814, 0.5726, 0.0676],
        [0.7382, 0.0738, 0.6554]])
tensor([[-0.1447, -1.2964, -0.1820,  0.2137],
        [ 0.1480,  0.4544, -1.3723, -0.8179],
        [-0.6222,  0.8877,  0.6213, -0.8331],
        [ 0.0937, -1.6094, -0.3361, -0.0601]])
tensor([[3, 0],
        [3, 4]])


In [13]:
# tensor from tensor

t_6 = torch.tensor([
    [1, 2],
    [2, 2]
])

print(t_6, t_6.shape)

tensor([[1, 2],
        [2, 2]]) torch.Size([2, 2])


In [14]:
# tensor of linespace

t_7 = torch.linspace(start=1, end=5, steps=5)

print(t_7)

tensor([1., 2., 3., 4., 5.])


In [17]:
# seed use

torch.manual_seed(1)
t_8 = torch.rand(size=(2, 2))

print(t_8)

tensor([[0.7576, 0.2793],
        [0.4031, 0.7347]])


In [19]:
torch.manual_seed(1)
t_9 = torch.rand(size=(2, 2))

print(t_9)

tensor([[0.7576, 0.2793],
        [0.4031, 0.7347]])


In [24]:
# eye; identity tensors


t_10 = torch.eye(n=10, m=3)
print(t_10)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [26]:
# like function

t_11 = torch.ones_like(t_10)
print(t_11)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


## Tensors types

In [34]:
# initialize tensor
t_01 = torch.randint(size=(3, 3), low=2, high=20)
t_03 = torch.randint(size=(3, 3), low=2, high=20, dtype=torch.float32)


print(f"tensor: \n{t_01}, \nshape: {t_01.shape}, type={t_01.dtype}")
print(f"tensor: \n{t_03}, \nshape: {t_03.shape}, type={t_03.dtype}")

tensor: 
tensor([[ 4, 17, 17],
        [ 9, 17, 19],
        [ 8,  4,  4]]), 
shape: torch.Size([3, 3]), type=torch.int64
tensor: 
tensor([[17.,  7.,  7.],
        [ 7., 11., 17.],
        [ 2., 17., 13.]]), 
shape: torch.Size([3, 3]), type=torch.float32


In [33]:
# cast the type into float

t_02 = t_01.to(torch.float32)

print(f"tensor: \n{t_02}, \nshape: {t_02.shape}, type={t_02.dtype}")

tensor: 
tensor([[10., 18., 17.],
        [ 2., 18., 10.],
        [19.,  6., 16.]]), 
shape: torch.Size([3, 3]), type=torch.float32


## Mathematical Operations

### Scalar Operations

In [39]:
# initialization

t_20 = torch.randint(size=(3, 3), low=2, high=20)
t_21 = torch.randint(size=(3, 3), low=2, high=40)
t_22 = torch.randint(size=(4, 4), low=20, high=80)

print(f"tensor: \n{t_20}, \nshape: {t_20.shape}")
print(f"tensor: \n{t_21}, \nshape: {t_21.shape}")
print(f"tensor: \n{t_22}, \nshape: {t_22.shape}")

tensor: 
tensor([[13,  5, 19],
        [18,  5,  2],
        [10, 11,  3]]), 
shape: torch.Size([3, 3])
tensor: 
tensor([[ 2, 31,  9],
        [ 2,  9, 20],
        [34, 19, 15]]), 
shape: torch.Size([3, 3])
tensor: 
tensor([[23, 62, 47, 37],
        [52, 27, 73, 73],
        [23, 66, 36, 56],
        [30, 70, 47, 75]]), 
shape: torch.Size([4, 4])


In [41]:
# addition

t_23 = t_20 + t_21


print(f"{t_20} \n+ \n{t_21}   \n\n{t_23}")

tensor([[13,  5, 19],
        [18,  5,  2],
        [10, 11,  3]]) 
+ 
tensor([[ 2, 31,  9],
        [ 2,  9, 20],
        [34, 19, 15]])   

tensor([[15, 36, 28],
        [20, 14, 22],
        [44, 30, 18]])


In [42]:
# subtraction

t_23 = t_20 - t_21


print(f"{t_20} \n- \n{t_21}   \n\n{t_23}")

tensor([[13,  5, 19],
        [18,  5,  2],
        [10, 11,  3]]) 
- 
tensor([[ 2, 31,  9],
        [ 2,  9, 20],
        [34, 19, 15]])   

tensor([[ 11, -26,  10],
        [ 16,  -4, -18],
        [-24,  -8, -12]])


In [48]:
print(torch.relu(t_23))

tensor([[6.5000, 0.1613, 2.1111],
        [9.0000, 0.5556, 0.1000],
        [0.2941, 0.5789, 0.2000]])


In [49]:
# subtraction

t_23_sub = t_20 - t_21


print(f"{t_20} \n- \n{t_21}   \n\n{t_23_sub}")
print(f"\nApplying ReLU to t_23_sub:\n{torch.relu(t_23_sub)}")

tensor([[13,  5, 19],
        [18,  5,  2],
        [10, 11,  3]]) 
- 
tensor([[ 2, 31,  9],
        [ 2,  9, 20],
        [34, 19, 15]])   

tensor([[ 11, -26,  10],
        [ 16,  -4, -18],
        [-24,  -8, -12]])

Applying ReLU to t_23_sub:
tensor([[11,  0, 10],
        [16,  0,  0],
        [ 0,  0,  0]])


In [43]:
# multiplication

t_23 = t_20 * t_21


print(f"{t_20} \n* \n{t_21}   \n\n{t_23}")

tensor([[13,  5, 19],
        [18,  5,  2],
        [10, 11,  3]]) 
* 
tensor([[ 2, 31,  9],
        [ 2,  9, 20],
        [34, 19, 15]])   

tensor([[ 26, 155, 171],
        [ 36,  45,  40],
        [340, 209,  45]])


In [45]:
# division

t_23 = t_20 / t_21


print(f"{t_20} \n/ \n{t_21}   \n\n{t_23}")

tensor([[13,  5, 19],
        [18,  5,  2],
        [10, 11,  3]]) 
/ 
tensor([[ 2, 31,  9],
        [ 2,  9, 20],
        [34, 19, 15]])   

tensor([[6.5000, 0.1613, 2.1111],
        [9.0000, 0.5556, 0.1000],
        [0.2941, 0.5789, 0.2000]])


In [46]:
# power

t_23 = t_20 / t_21


print(f"{t_20} \n* \n{t_21}   \n\n{t_23}")

tensor([[13,  5, 19],
        [18,  5,  2],
        [10, 11,  3]]) 
* 
tensor([[ 2, 31,  9],
        [ 2,  9, 20],
        [34, 19, 15]])   

tensor([[6.5000, 0.1613, 2.1111],
        [9.0000, 0.5556, 0.1000],
        [0.2941, 0.5789, 0.2000]])


## Reduction operation

In [59]:
# climp

t_1 = torch.randint(size=(2, 2, 2), low=2, high=10)
# t_2 = torch.clamp(t_1, min=0, max=40)


print(t_1)
# print(t_2)

tensor([[[6, 8],
         [6, 9]],

        [[9, 7],
         [6, 3]]])


In [75]:
torch.sum(torch.tensor([
                        [[6, 8],
                         [6, 9]],

                        [[2, 3],
                         [4, 4]]

                        ]), dim=0)

tensor([[ 8, 11],
        [10, 13]])

In [76]:
# sum

# 0: mean column
# 1: mean row
t_3 = torch.sum(t_1, dim=1)

print(t_3)

tensor([[12, 17],
        [15, 10]])


# cpu & gpu tensors

In [84]:
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

print(device)

cpu


In [79]:
# cpu tensor

c_t = torch.tensor([[2, 2], [4, 4]])

print(c_t, c_t.device)

tensor([[2, 2],
        [4, 4]]) cpu


In [85]:
# gpu tensor

g_t = torch.tensor([2, 3, 4], device=device)


print(c_t, c_t.device)

tensor([[2, 2],
        [4, 4]]) cpu
